# Configures Regal rules, see https://docs.styra.com/regal/category/rules
---
rules:
  style:
    todo-comment:
      level: warning
    file-length:
      level: warning
    line-length:
<<<<<<< HEAD
      max-line-length: 130
  idiomatic:
    no-defined-entrypoint:
      level: ignore
=======
      level: warning
>>>>>>> c4d3317 (regal lint is in conflict with opa fmt on the line-length)
