# Configures Regal rules, see https://docs.styra.com/regal/category/rules
---
rules:
  style:
    todo-comment:
      level: warning
    file-length:
      level: warning
    line-length:
      level: warning
    rule-length:
      max-rule-length: 50
  idiomatic:
    no-defined-entrypoint:
      level: ignore
