apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
  creationTimestamp: "2023-10-16T20:33:18Z"
  finalizers:
  - chains.tekton.dev/pipelinerun
  generation: 1
  labels:
    tekton.dev/pipeline: simple-build
  name: simple-build-run-ojhba
  namespace: default
  resourceVersion: "19864"
  uid: a5e7fada-74a5-41d7-863a-c54dd6044df8
spec:
  params:
  - name: IMAGE_DIGEST
    value: sha256:4eb51754b85eef1fff2e8dcb19a1b36b4034e8f483ae62b6c9ee054724439534
  - name: IMAGE_URL
    value: quay.io/lucarval/test-policies-chains
  - name: TEST_OUTPUT
    value: missing
  - name: commit
    value: e6ec5783167d8071c0e4113e2eb647278f25e455
  - name: committer-date
    value: "1697488398"
  - name: url
    value: gitspam.spam/spam/spam
  pipelineRef:
    name: simple-build
  taskRunTemplate:
    serviceAccountName: default
  timeouts:
    pipeline: 1h0m0s
status:
  childReferences:
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-ojhba-git-clone
    pipelineTaskName: git-clone
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-ojhba-scan
    pipelineTaskName: scan
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: simple-build-run-ojhba-build
    pipelineTaskName: build
  completionTime: "2023-10-16T20:33:31Z"
  conditions:
  - lastTransitionTime: "2023-10-16T20:33:31Z"
    message: 'Tasks Completed: 3 (Failed: 0, Cancelled 0), Skipped: 0'
    reason: Succeeded
    status: "True"
    type: Succeeded
  pipelineSpec:
    params:
    - name: commit
      type: string
    - name: url
      type: string
    - name: committer-date
      type: string
    - name: IMAGE_URL
      type: string
    - name: IMAGE_DIGEST
      type: string
    - name: TEST_OUTPUT
      type: string
    results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.build.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.build.results.IMAGE_DIGEST)
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.git-clone.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.git-clone.results.commit)
    tasks:
    - name: git-clone
      params:
      - name: commit
        value: e6ec5783167d8071c0e4113e2eb647278f25e455
      - name: url
        value: gitspam.spam/spam/spam
      - name: committer-date
        value: "1697488398"
      taskRef:
        kind: Task
        params:
        - name: url
          value: https://github.com/lcarva/ec-policies.git
        - name: revision
          value: 67f9db6765692ac4a67c03d405a103b3d82ba6d6
        - name: pathInRepo
          value: integration/task/mock-git-clone.yaml
        resolver: git
    - name: scan
      params:
      - name: TEST_OUTPUT
        value: missing
      runAfter:
      - git-clone
      taskSpec:
        description: This is a dummy task that emulates a task that scans source code.
          Its sole purpose is to facilitate testing.
        metadata: {}
        params:
        - description: The value to of the TEST_OUTPUT commit result.
          name: TEST_OUTPUT
          type: string
        results:
        - description: The summary scanner output.
          name: TEST_OUTPUT
          type: string
        spec: null
        steps:
        - computeResources: {}
          env:
          - name: TEST_OUTPUT
            value: missing
          image: registry.access.redhat.com/ubi9:latest
          name: scan
          script: |
            #!/usr/bin/env sh
            set -euo pipefail

            echo -n "${TEST_OUTPUT}" > "$(results.TEST_OUTPUT.path)"
    - name: build
      params:
      - name: IMAGE_URL
        value: quay.io/lucarval/test-policies-chains
      - name: IMAGE_DIGEST
        value: sha256:4eb51754b85eef1fff2e8dcb19a1b36b4034e8f483ae62b6c9ee054724439534
      runAfter:
      - scan
      taskRef:
        kind: Task
        params:
        - name: bundle
          value: quay.io/lucarval/test-policies-chains@sha256:120f3ea129b8ad55c48109bc9cd5066a5ecaffc233167adf371b6d27b36dbc2a
        - name: name
          value: mock-build
        - name: kind
          value: task
        resolver: bundles
  provenance:
    featureFlags:
      AwaitSidecarReadiness: true
      Coschedule: workspaces
      DisableAffinityAssistant: false
      DisableCredsInit: false
      EnableAPIFields: beta
      EnableProvenanceInStatus: true
      EnableTektonOCIBundles: false
      EnforceNonfalsifiability: none
      MaxResultSize: 4096
      RequireGitSSHSecretKnownHosts: false
      ResultExtractionMethod: termination-message
      RunningInEnvWithInjectedSidecars: true
      ScopeWhenExpressionsToTask: false
      SendCloudEventsForRuns: false
      SetSecurityContext: false
      VerificationNoMatchPolicy: ignore
  results:
  - name: IMAGE_URL
    value: quay.io/lucarval/test-policies-chains
  - name: IMAGE_DIGEST
    value: sha256:4eb51754b85eef1fff2e8dcb19a1b36b4034e8f483ae62b6c9ee054724439534
  - name: CHAINS-GIT_URL
    value: gitspam.spam/spam/spam
  - name: CHAINS-GIT_COMMIT
    value: e6ec5783167d8071c0e4113e2eb647278f25e455
  startTime: "2023-10-16T20:33:18Z"
