= RPM Repos Package

This package defines rules to confirm that all RPM packages listed in SBOMs specify a known and permitted repository id.

== Package Name

* `rpm_repos`

== Rules Included

[#rpm_repos__ids_known]
=== link:#rpm_repos__ids_known[All rpms have known repo ids]

Each RPM package listed in an SBOM must specify the repository id that it comes from, and that repository id must be present in the list of known and permitted repository ids. Currently this is rule enforced only for SBOM components created by cachi2.

*Solution*: Ensure every rpm comes from a known and permitted repository, and that the data in the SBOM correctly records that.

* Rule type: [rule-type-indicator failure]#FAILURE#
* FAILURE message: `RPM repo id check failed: %s`
* Code: `rpm_repos.ids_known`
* To exclude this rule, add `rpm_repos.ids_known` to the `exclude` list in your policy config. You can also exclude the entire package with `rpm_repos`, or exclude by collection with `@collection-name`.
* Effective from: `2024-11-10T00:00:00Z`
* https://github.com/conforma/policy/blob/{page-origin-refhash}/policy/release/rpm_repos/rpm_repos.rego#L40[Source, window="_blank"]

[#rpm_repos__rule_data_provided]
=== link:#rpm_repos__rule_data_provided[Known repo id list provided]

A list of known and permitted repository ids should be available in the rule data.

*Solution*: Include a data source that provides a list of known repository ids under the 'known_rpm_repositories' key under the top level 'rule_data' key. This list can extended with the 'extra_rpm_repositories' rule data key. The contents of both lists are combined.

* Rule type: [rule-type-indicator failure]#FAILURE#
* FAILURE message: `Rule data '%s' has unexpected format: %s`
* Code: `rpm_repos.rule_data_provided`
* To exclude this rule, add `rpm_repos.rule_data_provided` to the `exclude` list in your policy config. You can also exclude the entire package with `rpm_repos`, or exclude by collection with `@collection-name`.
* https://github.com/conforma/policy/blob/{page-origin-refhash}/policy/release/rpm_repos/rpm_repos.rego#L18[Source, window="_blank"]
