---
name: Pre-merge CI

on:
  pull_request:
    branches:
    - main

  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install opa
      run: make install-opa OPA_BIN=$HOME/.local/bin

    - name: Run checks
      run: make ci

    - name: Install gomplate
      run: make install-gomplate GOMPLATE_BIN=$HOME/.local/bin

    - name: Build docs
      run: make docs

    - name: Save docs
      uses: actions/upload-artifact@v3
      with:
        name: docs.md
        path: docs-build/docs.md
